jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.

- run:
    shell: /bin/sh
    command: |
      echo "Validating SHA"
      sha=$(git rev-parse HEAD)
      echo "Sha: $sha"
      firstletter=${sha:0:1}

      if [ $firstletter = "0" ]; then
        echo "Seems fine to me"
      else
        echo "Commit SHA must begin with 0"
        exit 1
      fi
